# Generated by Django 4.1 on 2022-08-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('describe', models.TextField()),
                ('date_init', models.DateField()),
                ('date_end', models.DateField()),
                ('concluid_project', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_technologie', models.CharField(max_length=20, unique=True)),
                ('type_technologie', models.CharField(choices=[('F', 'Front-end'), ('B', 'Back-end'), ('FS', 'Full-stack')], max_length=2)),
            ],
        ),
    ]
