# Generated by Django 4.1 on 2022-08-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technologie',
            old_name='name_technologie',
            new_name='name',
        ),
    ]
